apiVersion: beta/v1
kind: Deployment

metadata:
  name: stablecoin-contract
  version: 1.0.0

spec:
  deployer:
    wallet:
      type: privateKey
      value: "${PRIVATE_KEY}"
    gasSettings:
      gasLimit: 3000000

  package:
    name: StableCoin

  constructorArgs:
    - name: "name_"
      type: "string"
      value: "MockUSDC"
    - name: "symbol_"
      type: "string"
      value: "mUSDC"
    - name: "decimals_"
      type: "uint8"
      value: 6

  network:
    chainId: "${CHAIN_ID}"
    rpcUrl: "${RPC_URL}"
